services:
  app:
    build:
      context: ./app
      dockerfile: ../.docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
